### ISSUE TITLE
Some Problem

### ISSUE THREAD

**Issue by PACEJJ27** [odzhan/injection#1]
Why all kinds of payload is a pop-up box of shutdown.
such as calc.exe and notepad.exe , it doesn't work.

**Comment by odzhan** [comment]
These were tested on 64-bit versions of Windows 7 and 10. What operating system are you using?

**Comment by PACEJJ27** [comment]
Windows7 Pro  64-bit  Service Pack 1.
![1](https://user-images.githubusercontent.com/21055456/45727672-4e504600-bbf7-11e8-8cff-241131bb9f2c.png)
Sometimes,when I run these(calc.exe , notepad.exe , xbin.exe) ,It also cause explorer to crash.

**Comment by odzhan** [comment]
Use the files with .BIN extension as payload. Using an EXE won't work.

**Comment by PACEJJ27** [comment]
Problem solved.Thank you!
