### ISSUE TITLE
Just a word from me!

### ISSUE THREAD

**Issue by loneicewolf** [odzhan/injection#12]
### Hello!

note, this is not a "issue" or a 'problem' but more of a comment.

I just wanted to say Thanks for making this repo, It is very good;
⚡ and keep it up! 

Wishes! :)

**Comment by odzhan** [comment]
thank you! Must clean up the code soon as it's probably outdated now..

**Comment by loneicewolf** [comment]
@odzhan code being out of date or outdated doesn't mean it absolutely must be cleaned up but I appreciate it; keep on going! 
now ill not reply more here, you're probably busy either way; but yea :) watching your repos closely as they are very very well structured. They (in my opinion anyway) should be used as "examples" of how to make good github repos. it's brilliant.

# Regards from Sweden!
