### ISSUE TITLE
How to compile the payload file used on win 7 32-bit system?

### ISSUE THREAD

**Issue by Addtree** [odzhan/injection#4]
I tried to compile a payload file under win 7 32-bit system, but I failed, the screenshot is as follows
![image](https://user-images.githubusercontent.com/29371149/50500672-dd3deb80-0a8d-11e9-9c1e-0acc5835232b.png)
system version screenshot
![image](https://user-images.githubusercontent.com/29371149/50500783-766d0200-0a8e-11e9-940f-386c5c5e986c.png)
After I selected your bat file in vstools and executed your bat file, the generated payload.exe64.bin can be perfectly injected and played on the x64 system, so I am sure that my compilation method should be correct. After many attempts, I Found that it should be your file problem, after viewing in CFF found that xbin.exe and payload.exe are files under x64 platform, so the bin file under my compiled x32 platform always crashes or does not respond when injected. Can you upload the compiled 32-bit platform payload.exe and xbin.exe to github? Thank you very much, this problem has been bothering me for a long time.
xbin.exe  and payload.exe screenshot
![image](https://user-images.githubusercontent.com/29371149/50500974-b2ed2d80-0a8f-11e9-9f1d-4eb8f5b9e356.png)
![image](https://user-images.githubusercontent.com/29371149/50500984-c26c7680-0a8f-11e9-929a-86b6dc290979.png)

**Comment by odzhan** [comment]
Check the x86 folder in payload. chost.c doesn't work, but i might try fix it later.

**Comment by Qfoxsay** [comment]
How to compile the payload file used on win 7 64-bit system?
