### ISSUE TITLE
About the injection technology mentioned in your article Windows Process Injection Service Control Handler, I can not achieve after trying, is not my use is wrong, please help me, I am also in the win x64 system, have to say, from Your article has learned a lot of knowledge

### ISSUE THREAD

**Issue by Addtree** [odzhan/injection#5]
This is my screenshot:

![image](https://user-images.githubusercontent.com/29371149/50545202-c5f62e00-0c46-11e9-9b11-2bdb62255492.png)

Please use a diagram to show a usage

**Comment by odzhan** [comment]
Try eventlog instead. Notepad will be executed by the service hosting eventlog, but you can only see that using process explorer. Get a list of services with : sc query.

**Comment by Addtree** [comment]
I am sorry，but I don't know how to do，I have to been  compile svcctrl.c with /DLEGACY.Please tell me next how to do svcctrl.exe.I try to execute svcctrl.exe with arg,but......

![image](https://user-images.githubusercontent.com/29371149/50553786-df4fb680-0ce8-11e9-8fb4-1251b8e1a133.png)

![image](https://user-images.githubusercontent.com/29371149/50553792-18882680-0ce9-11e9-97ce-73bd186286f7.png)

**Comment by odzhan** [comment]
Looks like it is working fine. You just need to supply the service name.

**Comment by Addtree** [comment]
But why the payload is not injected into the service process, but also the payload you provide, use procexp to view there is no calc process

**Comment by odzhan** [comment]
The payload now runs notepad instead of calc. I had to switch from calc.exe to notepad.exe because calculator is a metro application on Windows 10 and won't execute inside a service host process. Use 'eventlog' as a test vector. The code works for me in most cases, so if it's not working for you, I have no idea what the problem is.
